apiVersion: v1
kind: Service
metadata:
  name: r8
spec:
  selector:
    app: r8
  ports:
    - port: 4002
      targetPort: 4002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r8
  template:
    metadata:
      labels:
        app: r8
    spec:
      containers:
        - name: r8
          image: r8:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: REDIS
              value: redis://redis:6379
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: ELASTICSEARCH_NODE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ELASTICSEARCH_NODE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: GOOGLE_CALLBACK_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_PORT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
            - name: PORT_R8
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PORT_R8
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASS
          livenessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1000m'
