apiVersion: v1
kind: Service
metadata:
  name: searchengine
spec:
  selector:
    app: searchengine
  ports:
    - port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchengine
  template:
    metadata:
      labels:
        app: searchengine
    spec:
      containers:
        - name: searchengine
          image: searchengine:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          env:
            - name: REDIS
              value: redis://redis:6379
            - name: ELASTICSEARCH_NODE
              value: http://elasticsearch:9200
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_HOST
            - name: PORT_SEARCH
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PORT_SEARCH
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_PORT
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"