// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface GetUserRequest {
  id: string;
}

export interface UserResponse {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** optional field */
  username?: string | undefined;
  name: string;
  email: string;
  avatar: string;
}

export interface GoogleAuthRequest {
  email: string;
  avatar: string;
  provider: string;
  name: string;
}

export interface GoogleAuthResponse {
  accessToken: string;
  refreshToken: string;
}

export interface ValidationRequest {
  id: string;
}

export interface VerificationRequest {
  token: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  getUser(request: GetUserRequest): Observable<UserResponse>;

  googleAuth(request: GoogleAuthRequest): Observable<GoogleAuthResponse>;

  validation(request: ValidationRequest): Observable<UserResponse>;

  verification(request: VerificationRequest): Observable<UserResponse>;
}

export interface AuthServiceController {
  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  googleAuth(
    request: GoogleAuthRequest,
  ): Promise<GoogleAuthResponse> | Observable<GoogleAuthResponse> | GoogleAuthResponse;

  validation(request: ValidationRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  verification(request: VerificationRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUser", "googleAuth", "validation", "verification"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
