// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: media.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "media";

export interface UploadMediaItem {
  entityType: string;
  mime: string;
  size: string;
  description?: string | undefined;
}

export interface UploadMediaRequest {
  entityId: string;
  items: UploadMediaItem[];
}

export interface UploadMediaResponse {
  /** doubles as idempotency key */
  batchId: string;
  entityId: string;
}

export interface FinaliseUploadRequest {
  batchId: string;
  entityId: string;
}

export interface FinaliseUploadResponse {
  batchId: string;
  status: string;
  readyCount: number;
}

export const MEDIA_PACKAGE_NAME = "media";

export interface MediaServiceClient {
  initiateUpload(request: UploadMediaRequest): Observable<UploadMediaResponse>;

  finaliseUpload(request: FinaliseUploadRequest): Observable<FinaliseUploadResponse>;
}

export interface MediaServiceController {
  initiateUpload(
    request: UploadMediaRequest,
  ): Promise<UploadMediaResponse> | Observable<UploadMediaResponse> | UploadMediaResponse;

  finaliseUpload(
    request: FinaliseUploadRequest,
  ): Promise<FinaliseUploadResponse> | Observable<FinaliseUploadResponse> | FinaliseUploadResponse;
}

export function MediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["initiateUpload", "finaliseUpload"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_SERVICE_NAME = "MediaService";
