syntax = "proto3";

package media;

service MediaService {
  rpc InitiateUpload (UploadMediaRequest) returns (UploadMediaResponse);
  rpc FinaliseUpload (FinaliseUploadRequest) returns (FinaliseUploadResponse);
}

message UploadMediaItem {
  string mime = 1;
  string size = 2;
  optional string description = 3;
}

message UploadMediaRequest {
  string entityId = 1;
  repeated UploadMediaItem items = 2;
}


message UploadMediaResponse {
  string batchId = 1; //doubles as idempotency key
  string entityId = 2;
}

message FinaliseUploadRequest {
  string batchId = 1;
  string entityId = 2;
}

message FinaliseUploadResponse {
  string batchId = 1;
  string status = 2;
  int32 readyCount = 3;
}